[preprod]

host = "snowhouse.preprod8.us-west-2.aws.snowflakecomputing.com"
database = "TEMP"
schema = "JDALLATEZZA"
role = "ENGINEER"
account = "snowhouse"
user = "jdallatezza"
warehouse = "SNOWHOUSE"
authenticator = "EXTERNALBROWSER"

[tt004029]

host = "snowflake.temptest004029.us-west-2.aws.snowflakecomputing.com"
database = "scratch"
schema = "public"
# role = "ENGINEER"
account = "snowflake"
user = "admin"
password = "test"
warehouse = "depaut_xs"
 
[tt000006]

host = "snowflake.temptest000006.us-west-2.aws.snowflakecomputing.com"
database = "tlee_test"
schema = "test"
# role = "ENGINEER"
account = "snowflake"
user = "admin"
password = "test"
warehouse = "tlee_wh"

[tt004047]

host = "snowflake.temptest004047.us-west-2.aws.snowflakecomputing.com"
database = "tlee_test"
schema = "test"
# role = "ENGINEER"
account = "snowflake"
user = "admin"
password = "test"
warehouse = "tlee_wh"


[local]

host = "snowflake.dev.local"
port = "53400"
protocol = "http"
account = "snowflake"
user = "admin"
password = "test"
warehouse = "tlee_wh"
database = "tlee_test"
schema = "test"
